# Generated by Django 2.2 on 2019-04-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='主题', max_length=50)),
                ('actor', models.CharField(default='演员', max_length=50)),
            ],
        ),
    ]
